name: Client Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        working-directory: client
      - name: Bundle Modules
        run: npm run build
        working-directory: client
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: japan-client
          path: client/build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: japan-client
          path: client/build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./client
