name: Server Build

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        working-directory: server
      - name: Bundle Modules
        run: npm run build
        working-directory: server
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: japan-server
          path: server/dist
